services:
#  mindjunkies:
#    depends_on:
#      - postgres_db
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: mindjunkies
#    environment:
#      - PORT=8080
#    env_file:
#      - .env
#    ports:
#      - "8080:8080"
#    entrypoint: [ "sh", "-c", "chmod +x /app/migrate.sh /app/entrypoint.sh && /app/migrate.sh && /app/entrypoint.sh" ]
#    volumes:
#      - staticfiles:/app/staticfiles

  postgres_db:
    image: postgres:latest
    restart: always
    command: -p 5434
    env_file:
      - .env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_db:
    image: redis:latest
    restart: always
    expose:
      - 6389
    ports:
      - "6389:6389"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6389


volumes:
  staticfiles:
    external: true
  postgres_data:
  redis_data: