services:
  mindjunkies:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    image: mindjunkies
    environment:
      - PORT=8080
    env_file:
      - .env
    ports:
      - "8080:8080"
    entrypoint: [ "sh", "-c", "chmod +x /app/migrate.sh /app/entrypoint.sh && /app/migrate.sh && /app/entrypoint.sh" ]

  postgres_db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: