services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    # environment:
    #   - REDIS_PASSWORD=cdhhwfjw8jdjs  # Add this line for Redis password
    # command: ["redis-server", "--requirepass", "cdhhwfjw8jdjs"]  # Require Redis password
    restart: always  

volumes:
  esdata01:
