# Generated by Django 5.1.5 on 2025-02-19 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='lectur_videos/')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='lecture.lecture')),
            ],
        ),
    ]
