# Generated by Django 5.1.7 on 2025-03-19 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0002_remove_forumtopic_like_count_forumtopic_reaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumreply",
            name="like_count",
        ),
        migrations.AddField(
            model_name="forumreply",
            name="reaction",
            field=models.ManyToManyField(
                related_name="liked_forum_topics", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
