# Generated by Django 5.1.7 on 2025-03-21 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_enrollment_payment_status_enrollment_transaction_id"),
        ("forums", "0003_remove_forumreply_like_count_forumreply_reaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumreply",
            name="reaction",
        ),
        migrations.RemoveField(
            model_name="forumtopic",
            name="reaction",
        ),
        migrations.AddField(
            model_name="forumreply",
            name="reactions",
            field=models.ManyToManyField(
                blank=True,
                related_name="forum_reply_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="forumtopic",
            name="module",
            field=models.ForeignKey(
                default="72f6570f-ef68-417d-9560-31045461d40d",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_posts",
                to="courses.module",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="forumtopic",
            name="reactions",
            field=models.ManyToManyField(
                blank=True,
                related_name="forum_topic_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="forumtopic",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forum_posts",
                to="courses.course",
            ),
        ),
        migrations.DeleteModel(
            name="ForumNotification",
        ),
    ]
