# Generated by Django 5.1.7 on 2025-03-24 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_forumcomment_likedcomment_likedreply_reply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Forum Comment'},
        ),
        migrations.AddField(
            model_name='reply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forums.reply'),
        ),
    ]
