# Generated by Django 5.1.7 on 2025-03-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_likedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedpost',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='forums.forumtopic'),
        ),
    ]
