# Generated by Django 5.1.7 on 2025-03-26 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_alter_likedpost_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumtopic',
            name='reactions',
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='likes',
            field=models.ManyToManyField(related_name='likedTopics', through='forums.LikedPost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likedpost',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.forumtopic'),
        ),
    ]
