# Generated by Django 5.1.7 on 2025-03-27 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0010_remove_forumtopic_reactions_forumtopic_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='likes',
            field=models.ManyToManyField(related_name='likedComments', through='forums.LikedComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
