# Generated by Django 5.1.7 on 2025-03-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0011_forumcomment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='content',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='content',
            field=models.CharField(max_length=150),
        ),
    ]
