apiVersion: batch/v1
kind: Job
metadata:
  name: django-collectstatic-job
  namespace: default
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: django-collectstatic
          image: registry.digitalocean.com/mindjunkies/django-mindjunkies-web:latest
          command: [ "/bin/bash", "-c", "/app/collectstatic.sh" ]
          envFrom:
            - secretRef:
                name: django-mindjunkies-prod-env
