apiVersion: batch/v1
kind: Job
metadata:
  name: django-rebuild-search-job
  namespace: default
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: django-rebuild-search
          image: registry.digitalocean.com/mindjunkies/django-mindjunkies-web:latest
          imagePullPolicy: Always
          command: [ "uv", "run", "python", "manage.py", "search_index", "--rebuild", "--noinput" ]
          envFrom:
            - secretRef:
                name: django-mindjunkies-prod-env
