# Generated by Django 5.1.6 on 2025-02-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='course_image',
            field=models.ImageField(blank=True, default='course_images/default.jpg', null=True, upload_to='course_images/'),
        ),
    ]
