# Generated by Django 5.1.7 on 2025-04-12 17:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturevideo',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
