# Generated by Django 5.1.5 on 2025-03-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturepdf",
            name="pdf_title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lecturevideo",
            name="video_title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
