# Generated by Django 5.1.6 on 2025-03-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0002_lecturepdf_pdf_title_lecturevideo_video_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturevideo",
            name="hls",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="lecturevideo",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lecturevideo",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails"),
        ),
    ]
