# Generated by Django 5.1.6 on 2025-03-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_lecturevideo_hls_lecturevideo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturevideo',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
