# Generated by Django 5.1.7 on 2025-04-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_lecture_unique_order_per_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastvisitedmodule',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lecture.lecturevideo'),
        ),
    ]
