# Generated by Django 5.1.7 on 2025-03-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0005_rename_content_lecture_learning_objective_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturepdf",
            name="pdf_title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lecturevideo",
            name="video_title",
            field=models.CharField(max_length=255),
        ),
    ]
