# Generated by Django 5.1.7 on 2025-03-19 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_enrollment_payment_status_enrollment_transaction_id"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("user", "course")},
        ),
    ]
