# Generated by Django 5.1.7 on 2025-04-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_balance_balancehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tran_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
