# Generated by Django 5.1.7 on 2025-03-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_managers"),
        ("accounts", "0008_user_is_teacher"),
    ]

    operations = []
