# Generated by Django 5.1.7 on 2025-03-29 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollment",
            old_name="student",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("course", "user")},
        ),
        migrations.AddField(
            model_name="enrollment",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "Teacher"),
                    ("assistant", "Assistant"),
                    ("student", "Student"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
