# Generated by Django 5.1.6 on 2025-03-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_alter_courseteacher_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="number_of_enrollments",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
