# Generated by Django 5.1.7 on 2025-03-29 05:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_rename_student_enrollment_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollment",
            old_name="user",
            new_name="student",
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("course", "student")},
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="role",
        ),
    ]
