# Generated by Django 5.1.6 on 2025-03-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_number_of_enrollments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="learnings",
            new_name="learning_objectives",
        ),
    ]
