# Generated by Django 5.1.7 on 2025-03-14 19:06

import django.db.models.deletion
import django.db.models.manager
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_course_preview_video_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("description", models.TextField(blank=True, null=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="courses.coursecategory",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Course Categories",
            },
            managers=[
                ("tree", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="courses.coursecategory",
            ),
        ),
    ]
