# Generated by Django 5.1.7 on 2025-03-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_coursecategory_course_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
