# Generated by Django 5.1.7 on 2025-03-25 07:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_enrollment_payment_status_enrollment_transaction_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
        migrations.AddField(
            model_name="course",
            name="searchable",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["searchable"], name="courses_cou_searcha_851483_gin"
            ),
        ),
    ]
