# Generated by Django 5.1.7 on 2025-04-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='preview_video',
        ),
        migrations.RemoveField(
            model_name='module',
            name='details',
        ),
    ]
