<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-28 12:46
=======
# Generated by Django 5.1.7 on 2025-04-28 12:45
>>>>>>> 81800275064826745c81488edeba24949b4305c0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_course_preview_video_remove_module_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
