name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [test-deployment-do, deployment-digitalocean]
  pull_request:
    branches: [test-deployment-do, deployment-digitalocean]

jobs:
  sonarqube:
    uses: Learnathon-By-Geeky-Solutions/mindjunkies/.github/workflows/sonarqube.yml@test-deployment-do
  build:
    runs-on: ubuntu-latest
    needs: [sonarqube]
    env:
      CLUSTER_NAME: django-mindjunkies
      SECRET_KEY: test-key-not-good-maybe-make-one-better
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: Login to DO Container Registry with short-lived token
        run: doctl registry login --expiry-seconds 1200
      - name: Build container image
        working-directory: .
        run: |
          docker build -f Dockerfile \
            -t registry.digitalocean.com/mindjunkies/django-mindjunkies-web:latest \
            -t registry.digitalocean.com/mindjunkies/django-mindjunkies-web:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
            .
      - name: Push image
        run: |
          docker push registry.digitalocean.com/mindjunkies/django-mindjunkies-web --all-tags
          - name: K8s cluster kubeconfig file with/ short-lived creds
            run: |
              doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}