name: Build Docker Container & Push to DO Registry

on:
  push:
    branches: [test-deployment-do]
  pull_request:
    branches: [test-deployment-do]

jobs:
  test_django_job:
    uses: Learnathon-By-Geeky-Solutions/mindjunkies/.github/workflows/test-django.yaml@test-deployment-do
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      DJANGO_SECRET_KEY: test-key-not-good-maybe-make-one-better
    steps:
      - name: Checkout code
        uses: actions/checkout@v2